# Generated by Django 2.0.5 on 2018-09-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdb',
            fields=[
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mobileno', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('bloodgroup', models.CharField(max_length=5)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('aad', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('app', models.IntegerField()),
            ],
        ),
    ]
