# Generated by Django 2.0.5 on 2018-09-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowuser', '0002_license_marriagecert_pancard_passport_votercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='pincodedb',
            fields=[
                ('pin', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pincodelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinc', models.CharField(max_length=7)),
                ('pinl', models.ForeignKey(on_delete=True, to='lowuser.userdb')),
            ],
        ),
    ]
